[tasks.resetbluetooth]
description = "reset bluetooth"
run = '''
export LANG=C

sudo hciconfig hci0 down
sudo hciconfig hci0 up
sudo systemctl restart bluetooth.service
sudo systemctl status bluetooth.service
'''

[tasks.upgrademise]
description = "upgrade mise"
run = '''
echo "# upgrade mise"
export LANG=C
mise self-update
mise up
'''
alias = "upmise"
depends = ["upgradeapt"]

[tasks.upgradeuv]
description = "upgrade uv"
run = '''
echo "# upgrade uv"
export LANG=C
uv tool upgrade --all
'''
alias = "upuv"
depends = ["upgrademise"]

[tasks.upgradeproject]
description = "upgrade in this project"
run = '''
# upgrade this project

echo "# rm -f uv.lock"
rm -f uv.lock
echo "# uv sync"
uv sync

echo "# pip"
uv pip install -U --group dev -e .
# uv pip install -U --group samples -e .
'''
alias = "upproj"
# depends = ["upgradeuv"]

[tasks.lint]
description = "linting"
run = '''
# format and linting

echo "# ruff"
uv run ruff format --line-length 78 src samples tests
uv run ruff check --fix --extend-select I  src samples tests

echo "# pyright"
uv run pyright src samples

echo "# mypy"
uv run mypy src samples tests

uv run pibtinput -V
'''
depends = ["upgradeproject"]

[tasks.test]
description = "test"
run = '''
uv run pytest tests

uv run pibtinput -V
'''
depends = ["lint"]

[tasks.build]
description = "build"
run = '''
echo "# build"
rm -rf dist
uv build
uv run pibtinput -V
'''
depends = ["test"]

# [tasks.testpypi]
# description = "Test PyPI"
# run = '''
# pwd
# . ./.env
# uv run twine upload --verbose --repository-url https://test.pypi.org/legacy/ dist/* -u __token__ -p ${TESTPYPI_PASSWD}
# '''
# depends = ["build"]
